### ISSUE TITLE
Suggestion: Option to disable inline styles

### ISSUE THREAD

**Issue by benmurden** [shipshapecode/ember-shepherd#379]
The default styles appear to be added to a `<style>` tag in the head at runtime. These are frustrating and costly to override because many of them are very specific, leading to specificity wars. Furthermore, we can't use existing styles because anything the included styles define gets overridden, unless we make new, more specific definitions with exactly the same styles.

Shepherd docs mention not including the shepherd.css to avoid this, but this doesn't seem to be an option with this ember addon.

**Comment by rwwagner90** [comment]
@benmurden the docs are referring to Shepherd v6, and the published version of this addon was on v5. I just published ember-shepherd 10.0.0 which updates to Shepherd v6. We did a major refactor of Shepherd for this version, and the styles should be easier to override, since they are defined in a CSS file instead of injected as a style tag.

**Comment by benmurden** [comment]
@rwwagner90 Great, that would certainly help.
