### ISSUE TITLE
Way to get user to confirm quitting a tutorial

### ISSUE THREAD

**Issue by djsegal** [shipshapecode/ember-shepherd#56]
### What happened

I want to use a browser's native alert for confirming a tutorial quit.

I tried to monkey patch with the following code, but was unsuccessful:

```
    var route = this;
    Ember.$("body").on("click", ".shepherd-cancel-link", function(e){
      var stopTutorial = confirm('Are you sure you want to stop the tutorial?');
      if ( stopTutorial ) { return; }
      e.preventDefault();  // first attempt
      route.get('tour').start();   // second attempt 
    });
```

---------

#### 2 unsuccessful attempts

+ `e.preventDefault();` - you probably use ember bindings, rendering this useless
+ `route.get('tour').start();` - gets demo to start, but it's completely reset

**Comment by rwwagner90** [comment]
@djsegal I think the issue is all of our builtInButtons are still going to fire all of their events. So, to support this, I think we would need to allow using custom buttons too, and you would have to define a button that does the behavior you are looking for. I'm open to a PR that would allow custom buttons for other actions, other than the Shepherd supported ones.

**Comment by rwwagner90** [comment]
@djsegal we can totally support this in this addon. It looks like Shepherd allows you to pass events for buttons, so we would just need to allow passing that here and you could pass a `click` event function that would pop up a confirm, then after your confirm, you could manually do `this.get('tour').cancel()`

**Comment by rwwagner90** [comment]
@djsegal 2.1.5 should not have this functionality. Please update and give it a try!

**Comment by djsegal** [comment]
@rwwagner90 thank you! works like a charm
